---
title: "Publications"
title-block-banner-color: white
title-block-banner: media/IMG_2938_2.jpg
---

*(Please email me if you have any trouble accessing publications, I will happily send you a pdf!)*

Abrahms B.A., Rafiq K., **Nisi A.C.,** Jordan N.R., Wilson A.M., Loveridge A.J., Kotze R., Sousa L.L., McNutt J.W. [Intraguild competition mediates human avoidance in an endangered African large carnivore](http://doi.org/10.1098/rspb.2024.2835). *Proc. R. Soc. B* (2025) DOI: 10.1098/rspb.2024.2835

**Nisi A.C.**, Welch H., Brodie S., Leiphardt C., Rhodes R., Hazen E.L., Redfern J.V., Branch T.A., Barreto A.S., Calambokidis J., Clavelle T., Dares L., de Vos A., Gero S., Jackson J.A., Kenney R.D., Kroodsma D., Leaper R., McCauley D.J., Moore S., Ovsyanikova E., Panigada S., Robinson C.V., White T., Wilson J., Abrahms B. [Ship collision risk threatens whales across the world's oceans](https://www.science.org/doi/10.1126/science.adp1950). Science (2024). DOI: 10.1126/science.adp1950

-   *See related press coverage in [The Guardian](https://www.theguardian.com/environment/2024/nov/21/reduce-whale-ship-strikes-ocean-surface-safer-study), [The Seattle Times](https://www.seattletimes.com/seattle-news/climate-lab/ship-strikes-now-leading-cause-of-whale-deaths-uw-study-finds/), [Inside Climate News](https://insideclimatenews.org/news/21112024/whale-ship-collision-global-hotspots-lack-protections), [El País](https://elpais.com/ciencia/2024-11-21/los-puntos-negros-del-mar-los-barcos-mas-grandes-del-mundo-amenazan-el-habitat-de-las-ballenas.html), [Le Monde](https://www.lemonde.fr/planete/article/2024/11/21/les-baleines-du-monde-entier-menacees-par-le-risque-de-collision-avec-les-navires_6407466_3244.html), [Mongabay](https://news.mongabay.com/short-article/2024/11/protecting-oceans-prevent-whale-ship-collisions/), [National Geographic](https://www.nationalgeographic.com.es/ciencia/peligro-oculto-colisiones-entre-ballenas-y-barcos_23727), [Northwest Public Broadcasting](https://www.kuow.org/stories/whale-ship-collisions-around-the-globe-could-be-helped-by-slower-speeds-study-shows)*

Oliver R.Y., Chapman M., Emery N., Gillespie L., Gownaris N., Leiker S., **Nisi A.C.,** Ayers D., Breckheimer I., Blondin H., Hoffman A.M., Pagniello C., Raisle M., Zimmerman N. [Opening a conversation on responsible environmental data science in the age of generative AI](https://www.cambridge.org/core/journals/environmental-data-science/article/opening-a-conversation-on-responsible-environmental-data-science-in-the-age-of-large-language-models/95FD09526541A19436F3A18ADE332953). *Environmental Data Science* (2024). DOI: https://doi.org/10.1017/eds.2024.12

Clark-Wolf T.J., Holt K.A., Johansson E., **Nisi A.C.**, Rafiq K., West L., Boersma P.D., Hazen E.L., Moore S.E., Abrahms B.[The capacity of sentinel species to detect changes in environmental conditions and ecosystem structure](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1365-2664.14669). *Journal of Animal Ecology* (2024). DOI: 10.1111/1365-2664.14669

Benson J.F., Dougherty K.D., Beier P., Boyce W.M., Critescu B., Gammons D.J., Garcelon D.K., Higley J.M., Martins Q.E., **Nisi A.C.,** Riley S.P.D., Sikich J.A., Stephenson T.R., Vickers T.W., Wengert G.M., Wilmers C.C., Wittmer H.U., Dellinger J.A. [The Ecology of Human-Caused Mortality for a Protected Large Carnivore](https://www.pnas.org/doi/abs/10.1073/pnas.2220030120). *Proceedings of the National Academy of Sciences* (2023). DOI: 10.1073/pnas.2220030120

**Nisi A.C.,** Benson J.F., King R., Wilmers C.C. [Habitat fragmentation reduces survival and drives source-sink dynamics for a large carnivore](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/eap.2822). *Ecological Applications* (2023). DOI: 10.1002/eap.2822

-   *Recognized as a Top Cited Article in* Ecological Applications 

Abrahms B., Carter N.H., Clark-Wolf T., Gaynor K.M., Johansson E., McInturff A., **Nisi A.C.**, Rafiq K., West L. [Climate change as a global amplifier of human--wildlife conflict](https://www.nature.com/articles/s41558-023-01608-5). *Nature Climate Change* (2023). DOI: 10.1038/s41558-023-01608-5 

**Nisi A.C.**, Benson J.F., Wilmers C.C. [Puma responses to unreliable human cues suggest an ecological trap in a fragmented landscape](https://nsojournals.onlinelibrary.wiley.com/doi/full/10.1111/oik.09051). *Oikos* (2022). DOI: 10.1111/oik.09051

-   *Cover article, recognized as Top Downloaded Article in* Oikos

Armstrong J., **Nisi A.C.**, Millard-Ball A*.* [A disciplinary divide in the framing of urbanization's environmental impacts](https://conbio.onlinelibrary.wiley.com/doi/full/10.1111/csp2.624). *Conservation Science and Practice* (2022). DOI: 10.1111/csp2.624

**Nisi A.C.**, Suraci J.P., Ranc N., Frank L.G., Oriol-Cotterill A., Ekwanga S., Williams T.M., Wilmers C.C. [The temporal scale of habitat selection in large carnivores: balancing energetics, risk, and finding prey](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2656.13613). *Journal of Animal Ecology* (2022).DOI: 10.1111/1365-2656.13613

-   *Recognized as a Top Cited Article in* Journal of Animal Ecology

Wilmers C.C., **Nisi A.C.,** Nathan R.[COVID-19 suppression of human mobility releases mountain lions from a landscape of fear](https://www.cell.com/current-biology/fulltext/S0960-9822(21)00879-4). *Current Biology* (2021). DOI: 10.1016/j.cub.2021.06.050

Nickel B.A., Suraci J.P., **Nisi A.C.**, Wilmers C.C. [Energetics and fear of humans constrain the spatial ecology of pumas](https://www.pnas.org/doi/abs/10.1073/pnas.2004592118). *Proceedings of the National Academy of Sciences* (2021). DOI: 10.1073/pnas.2004592118

**Nisi A.C.**, Hernández DL, English LP, Rogers E. [Patterns of selective herbivory on five prairie legume species](https://bioone.org/journals/The-American-Midland-Naturalist/volume-173/issue-1/0003-0031-173.1.110/Patterns-of-Selective-Herbivory-on-Five-Prairie-Legume-Species/10.1674/0003-0031-173.1.110.short). *American Midland. Naturalist* (2015). DOI: 10.1674/0003-0031-173.1.110 

Witmer HU, Cristescu B, Spitz DB, **Nisi A.C.**, Wilmers C.C. Final Report: Siskiyou Deer-Puma Study (2015-2020). A report to the California Department of Fish and Wildlife (2020)​
